import JSZip from "jszip";
import {
  ARTIFACT_FILENAME,
  type PackagerInput,
  type PackagerOutput,
} from "./types";

/**
 * Portable system spec — the headlining artifact of the unlimited-license tier.
 *
 * Outputs a zip with:
 *   spec.json        — the full preset (tokens + content + tweaks merged)
 *   tokens.css       — palette + type as drop-in CSS variables
 *   content.md       — every content block formatted for review/translation
 *   block-order.json — the canonical 7-block CRO ordering
 *   README.md        — explains the bundle and how to reimplement on any stack
 *   LICENSE.txt      — traceability stamp + copyright + license key (if any)
 *
 * Every file in the zip is plain text, ~few KB total. No Liquid, no PHP, no
 * lock-in to a particular renderer.
 */
export async function packageSpec(
  input: PackagerInput,
): Promise<PackagerOutput> {
  const zip = new JSZip();
  const merged = { ...input.tokens, ...(input.tweaks ?? {}) };

  zip.file("spec.json", JSON.stringify(buildSpecJson(input), null, 2));
  zip.file("tokens.css", buildTokensCss(merged));
  zip.file("content.md", buildContentMarkdown(input));
  zip.file("block-order.json", JSON.stringify(BLOCK_ORDER, null, 2));
  zip.file("README.md", buildReadme(input));
  zip.file("LICENSE.txt", buildLicenseTxt(input));

  const bytes = await zip.generateAsync({
    type: "uint8array",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return {
    filename: ARTIFACT_FILENAME.spec(input.presetSlug),
    contentType: "application/zip",
    bytes,
  };
}

function buildSpecJson(input: PackagerInput) {
  return {
    $schema: "https://shoplanding.com/schema/landing-spec.v1.json",
    generatedAt: new Date().toISOString(),
    presetSlug: input.presetSlug,
    version: input.version,
    tokens: { ...input.tokens, ...(input.tweaks ?? {}) },
    content: input.content,
    blockOrder: BLOCK_ORDER,
  };
}

function buildTokensCss(t: Record<string, string | undefined>): string {
  const lines = [
    "/* Generated by ShopLanding · drop into your theme's root stylesheet. */",
    ":root {",
    `  --accent: ${t.accent ?? "#1f5a40"};`,
    `  --accent-deep: ${t.accentDeep ?? "#0f3a26"};`,
    `  --accent-soft: ${t.accentSoft ?? "#e6f0ea"};`,
    `  --ink: ${t.ink ?? "#0f0e0d"};`,
    `  --ink-2: ${t.ink2 ?? "#2a2823"};`,
    `  --muted: ${t.muted ?? "#807868"};`,
    `  --line: ${t.line ?? "#e3dac0"};`,
    `  --surface: ${t.surface ?? "#f5e6d6"};`,
    `  --bg: ${t.bg ?? "#faf7f1"};`,
    `  --font-display: ${t.fontDisplay ?? '"Fraunces", Georgia, serif'};`,
    `  --font-body: ${t.fontBody ?? '"Inter", system-ui, sans-serif'};`,
    `  --font-mono: ${t.fontMono ?? '"JetBrains Mono", ui-monospace, monospace'};`,
    "}",
    "",
  ];
  return lines.join("\n");
}

function buildContentMarkdown(input: PackagerInput): string {
  const c = input.content;
  const lines: string[] = [];
  lines.push(`# ${c.brand.name} — content reference`);
  lines.push("");
  lines.push(`Generated from preset \`${input.presetSlug}\` at ${new Date().toISOString()}.`);
  lines.push("");
  lines.push("## Product");
  lines.push(`- **Title:** ${c.product.title}`);
  lines.push(`- **Subtitle:** ${c.product.subtitle}`);
  lines.push(`- **Collection:** ${c.product.collection}`);
  lines.push(`- **Price:** $${c.product.price} (was $${c.product.was})`);
  lines.push(`- **Rating:** ${c.product.rating} from ${c.product.reviewCount} reviews`);
  lines.push("");
  lines.push("### Key benefits");
  for (const b of c.product.keyBenefits) lines.push(`- ${b}`);
  lines.push("");
  lines.push("## Brand");
  lines.push(`- **Name:** ${c.brand.name}`);
  lines.push(`- **Tagline:** ${c.brand.tagline}`);
  lines.push(`- **Founder:** ${c.brand.founderName} — ${c.brand.founderTitle}`);
  lines.push(`- **Quote:** "${c.brand.founderQuote}"`);
  lines.push("");
  lines.push("## FAQ");
  for (const f of c.faq) {
    lines.push(`### ${f.q}`);
    lines.push(f.a);
    lines.push("");
  }
  lines.push("## Specs");
  for (const [k, v] of c.specs) lines.push(`- **${k}:** ${v}`);
  lines.push("");
  return lines.join("\n");
}

function buildReadme(input: PackagerInput): string {
  return [
    `# ShopLanding · system spec`,
    ``,
    `**Preset:** \`${input.presetSlug}\`  `,
    `**Version:** ${input.version}  `,
    `**Generated:** ${new Date().toISOString()}`,
    ``,
    `This bundle is the portable, framework-agnostic spec for an optimized`,
    `single-product landing page. Drop it into Hydrogen, Astro, Webflow, Framer,`,
    `WordPress without Woo, or any system you can render HTML in.`,
    ``,
    `## Files`,
    ``,
    `- \`spec.json\` — full preset object: tokens, content, block order. The`,
    `  authoritative source.`,
    `- \`tokens.css\` — palette + type as CSS variables. Drop into your root`,
    `  stylesheet and every component picks up the brand instantly.`,
    `- \`content.md\` — every text block formatted for review, translation, or`,
    `  CMS import.`,
    `- \`block-order.json\` — the canonical 7-CRO-block sequence. Don't reorder`,
    `  silently — each block is here for a documented reason.`,
    `- \`LICENSE.txt\` — traceability + license key.`,
    ``,
    `## How to use`,
    ``,
    `1. Read \`spec.json\` to get the full content + token tree.`,
    `2. Implement the 7 blocks in \`block-order.json\` in order.`,
    `3. Apply \`tokens.css\` to your renderer's root scope.`,
    `4. Wire content from \`spec.json\` into each block.`,
    ``,
    `Updates: re-download this bundle any time. The preset and renderer evolve;`,
    `a fresh export reflects the latest CRO ruleset.`,
    ``,
    `Questions: support@shoplanding.com`,
    ``,
  ].join("\n");
}

function buildLicenseTxt(input: PackagerInput): string {
  const license = input.licenseKey ?? "(unlicensed dev export)";
  return [
    `ShopLanding theme system — license traceability stamp`,
    ``,
    `Preset:      ${input.presetSlug}`,
    `Version:     ${input.version}`,
    `Generated:   ${new Date().toISOString()}`,
    `License key: ${license}`,
    ``,
    `Use of this bundle is governed by the ShopLanding license tier`,
    `purchased with the above key. See https://shoplanding.com/license`,
    `for the current terms.`,
    ``,
  ].join("\n");
}

const BLOCK_ORDER = [
  { position: 0, slug: "general", purpose: "Page-level CRO baseline (4 rules)." },
  { position: 1, slug: "product-overview-above-the-cta-area", purpose: "Title, rating, key benefits above the CTA (6 rules)." },
  { position: 2, slug: "image-gallery", purpose: "Product imagery + zoom + thumbnails (9 rules)." },
  { position: 3, slug: "cta-area", purpose: "Buy box, variants, qty, urgency, sticky ATC (23 rules)." },
  { position: 4, slug: "social-proof", purpose: "Press, reviews, UGC, founder (8 rules)." },
  { position: 5, slug: "conversion-and-aov-boosters", purpose: "Bundles, subs, free-ship, cross-sell (9 rules)." },
  { position: 6, slug: "product-description", purpose: "Benefits, how it works, comparison, ingredients, specs, FAQ (10 rules)." },
];
